# Generated by Django 2.2.19 on 2022-05-13 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20220428_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='in_cart',
            field=models.ManyToManyField(related_name='recipe_in_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
