# Generated by Django 2.2.19 on 2022-05-20 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20220514_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorites', through='cookbook.Favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_cart_of',
            field=models.ManyToManyField(related_name='shopping', through='cookbook.Cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
