# Generated by Django 2.2.19 on 2022-05-21 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20220520_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(default=0, upload_to='cookbook/'),
            preserve_default=False,
        ),
    ]
